name: Manual Run WEB Tests
run-name: Agi - Manual Web Tests Run
on:
  workflow_dispatch:
    inputs:
      componente:
        type: string
        description: Qual é o COMPONENTE a ser executado?
        required: true
      tag:
        type: string
        description: Qual é a TAG a ser executada?
        required: true
      browser:
        type: string
        description: Qual é o BROWSER a ser executado?
        required: true

jobs:
  web-tests:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with: 
          node-version: '20'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          rfbrowser init

      - name: Run Agi Web Tests
        run: |
          robot --variable COMPONENTE:${{ inputs.componente }} --variable TAG:${{ inputs.tag }} --variable BROWSER:${{ inputs.browser }} controller.robot

      - name: Upload Tests Results
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: results-chrome
          path: ./results
          if-no-files-found: ignore
          retention-days: 2

      - name: Download Tests Results
        if: always()
        uses: actions/download-artifact@v1
        with: 
          name: results-chrome

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: results-chrome
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          pull_request_id: ${{ github.event.number }}

